name: event_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  google_fonts:
  badges:
  provider: ^6.1.2
  carousel_slider_plus: ^7.0.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_spinkit: ^5.2.1
  loading_animation_widget: ^1.3.0
  flutter_rating_bar: ^4.0.1
  connectivity_plus: ^6.0.5
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.4
  fluttertoast: ^8.2.8
  toastification: ^3.0.1
  top_snackbar_flutter: ^3.1.0
  cached_network_image: ^3.4.1
  dot_navigation_bar: ^1.0.2
  flutter_floating_bottom_bar: ^1.2.1+1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_smart_dialog: ^4.9.8+3
  country_code_picker: ^3.0.0
  photo_view: ^0.15.0
  image_picker: ^0.8.7
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  easy_stepper: ^0.8.5+1
  image_cropper: ^9.0.0
  device_info_plus: ^11.0.0
  camera: ^0.11.0+2
  webview_flutter: ^4.10.0
  intl: ^0.19.0
  auto_size_text: ^3.0.0
  persistent_bottom_nav_bar: ^6.2.1
  global_bottom_navigation_bar: ^0.0.8
  file_saver: ^0.2.14
  syncfusion_flutter_sliders:
  flutter_widget_from_html:
  camera_gallery_image_picker: ^0.0.4
  file_picker: ^9.0.2
  signature: ^6.0.0
  flutter_quill: ^11.4.1
  vsc_quill_delta_to_html: ^1.0.5
  getwidget: ^6.0.0
  modal_progress_hud_nsn: ^0.5.1
  syncfusion_flutter_datagrid: ^28.1.41
  dropdown_button2: ^2.3.9
  dio: ^5.7.0
  logger: ^2.5.0
  data_table_2: ^2.5.18
  flutter_quill_delta_from_html: ^1.5.0
  another_stepper: ^1.2.2
  open_file: ^3.5.10
  custom_date_range_picker: ^1.1.0
  dotted_border: ^2.1.0
  multi_dropdown: ^3.0.1
  html_unescape: ^2.0.0
  pdf: ^3.11.3
  flutter_pdfview: ^1.2.5
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.svg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/login/
    - assets/vendor_assets/settings/
    - assets/vendor_assets/drawer/
    - assets/vendor_assets/dashboard/
    - assets/vendor_assets/product/

  fonts:
    - family: FontSf
      fonts:
        - asset: fonts/sf-pro-display/sfprodisplaybold.otf
