name: event_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.1+18

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  google_fonts:
  badges:
  provider: ^6.1.5
  carousel_slider_plus: ^7.1.1
  shared_preferences: ^2.5.3
  flutter_spinkit: ^5.2.1
  loading_animation_widget: ^1.3.0
  flutter_rating_bar: ^4.0.1
  connectivity_plus: ^6.1.4
  flutter_html: ^3.0.0
  html: ^0.15.6
  fluttertoast: ^8.2.12
  toastification: ^3.0.2
  top_snackbar_flutter: ^3.3.0
  cached_network_image: ^3.4.1
  dot_navigation_bar: ^1.0.2
  flutter_floating_bottom_bar: ^1.3.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_smart_dialog: ^4.9.8+8
  country_code_picker: ^3.3.0
  photo_view: ^0.15.0
  image_picker: ^0.8.7
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  easy_stepper: ^0.8.5+1
  image_cropper: ^9.1.0
  device_info_plus: ^11.4.0
  camera: ^0.11.1
  webview_flutter: ^4.13.0
  auto_size_text: ^3.0.0
  persistent_bottom_nav_bar: ^6.2.1
  global_bottom_navigation_bar: ^0.0.8
  file_saver: ^0.2.14
  syncfusion_flutter_sliders:
  flutter_widget_from_html:
  camera_gallery_image_picker: ^0.0.4
  file_picker: ^10.1.9
  signature: ^6.0.0
  flutter_quill: ^11.4.1
  vsc_quill_delta_to_html: ^1.0.5
  getwidget: ^6.0.0
  modal_progress_hud_nsn: ^0.5.1
  syncfusion_flutter_datagrid: ^30.1.37
  dropdown_button2: ^2.3.9
  logger: ^2.5.0
  data_table_2: ^2.6.0
  flutter_quill_delta_from_html: ^1.5.2
  another_stepper: ^1.2.2
  open_file: ^3.5.10
  dotted_border: ^3.0.1
  multi_dropdown: ^3.0.1
  html_unescape: ^2.0.0
  pdf: ^3.11.3
  flutter_pdfview: ^1.4.0+1
  flutter_secure_storage: ^9.2.4
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  #  http: ^1.4.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  get_it: ^8.0.3
  printing: ^5.14.2
  syncfusion_flutter_pdf: ^30.2.5
  calendar_date_picker2: ^2.0.1

  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6

  path: any
dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/login/
    - assets/vendor_assets/settings/
    - assets/vendor_assets/drawer/
    - assets/vendor_assets/dashboard/
    - assets/vendor_assets/product/
    - assets/nav/

  fonts:
    - family: FontSf
      fonts:
        - asset: fonts/sf-pro-display/sfprodisplaybold.otf
